### PR TITLE
README: fix broken links

### PR DESCRIPTION
**Pull request by Harvester57**
I was not able to fix all the links (couldn't find a substitute for the NSA BIND 9 DNS Security page, for example), but it's a start ! :)

### CODE REVIEW

**Comment by Harvester57** [comment]
I beleive that @DanielRuf is the maintainer of the SSL Decoder and Cipherli.st substitutes that are reported as broken (I can't access them either), maybe he could have a look at them ?

**Comment by DanielRuf** [comment]
@Harvester57 thanks for the mention.

Yes those copies are not online anymore. There is probably an alternative solution still available: 

https://www.reddit.com/r/linuxadmin/comments/eyd9yp/cipherlist_appears_gone_again/

https://github.com/Brunty/awesome-checker-services

**Comment by Harvester57** [comment]
Thank you @DanielRuf for the clarification, I changed the Cipherli.st link to point to https://cipherlist.eu/ (looks like it's still up-to-date), but the SSL Decoder alternative is also broken, so I removed it entirely, since I wasn't able to find it anywhere :(

**Review by decalage2 — APPROVED** [review]
Thank you!

**Comment by decalage2** [comment]
SSL decoder source code seems to be here: https://github.com/RaymiiOrg/ssl-decoder

**Pull request merged**
